require("dotenv").config(); // add this as the very first line of server.js
const express = require("express");
const nodemailer = require("nodemailer");
const cors = require("cors");

const app = express();
app.use(cors());
app.use(express.json());

const transporter = nodemailer.createTransport({
  service: "gmail",
  auth: {
    user: process.env.EMAIL_USER,     // your gmail address
    pass: process.env.EMAIL_PASS,     // your gmail app password (not your real password)
  },
});

app.post("/send-results", async (req, res) => {
  console.log("Received body:", JSON.stringify(req.body));
  const { email, verdict } = req.body;
  const bars = verdict.bars;

  const barLabels = ["Skills Match", "Experience Level", "Domain Alignment", "Keywords"];
  const verdictColors = { "Good Fit": "#00E5A0", "Potential Fit": "#FFB830", "No Fit": "#FF4D6A" };
  const color = verdictColors[verdict.label] || "#6366F1";

  const barsHtml = barLabels.map((label, i) => `
    <tr>
      <td style="padding: 8px 0; color: #888; font-size: 13px;">${label}</td>
      <td style="padding: 8px 0; text-align: right; color: ${color}; font-family: monospace; font-size: 13px;">${bars[i]}%</td>
    </tr>
  `).join("");

  const html = `
    <div style="background:#0A0A0F; padding: 40px; font-family: 'DM Sans', sans-serif; max-width: 560px; margin: 0 auto; border-radius: 16px;">
      <p style="color:#666; font-size:11px; letter-spacing:0.15em; font-family:monospace; margin-bottom: 24px;">RESUME FIT ANALYZER · DATATHON 2026</p>

      <h1 style="font-size: 42px; margin: 0 0 4px; color: ${color}; letter-spacing: 0.04em;">
        ${verdict.label}
      </h1>
      <p style="color: #666; font-size: 14px; margin: 0 0 32px;">${verdict.tagline}</p>

      <div style="background: rgba(255,255,255,0.04); border: 1px solid rgba(255,255,255,0.08); border-radius: 12px; padding: 20px 24px; margin-bottom: 32px;">
        <table style="width:100%; border-collapse: collapse;">
          ${barsHtml}
        </table>
      </div>

      <p style="color: #444; font-size: 12px; border-top: 1px solid #1a1a1a; padding-top: 20px;">
        This result was generated by the Resume Fit Analyzer model trained at Datathon 2026.
      </p>
    </div>
  `;

  try {
    await transporter.sendMail({
      from: `"Resume Fit Analyzer" <${process.env.EMAIL_USER}>`,
      to: email,
      subject: `Your Resume Fit Result: ${verdict.label}`,
      html,
    });
    res.json({ success: true });
  } catch (err) {
    console.error(err);
    res.status(500).json({ success: false, error: err.message });
  }
});

app.listen(5001, () => console.log("Mail server running on http://localhost:5001"));